using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Shooter : MonoBehaviour
{
	[SerializeField] GameObject projectile;
	[SerializeField] GameObject gun;

	AttackerSpawner myLaneSpawner;
	Animator animator;
	GameObject projectileParent;
	const string PROJECTILE_PARENT_NAME = "Projectiles";

	private void Start()
	{
		SetLaneSpawner();
		animator = GetComponent<Animator>();
		CreateProjectileParent();
	}

	private void CreateProjectileParent()
	{
		projectileParent = GameObject.Find(PROJECTILE_PARENT_NAME);
		if (!projectileParent)
		{
			projectileParent = new GameObject(PROJECTILE_PARENT_NAME);
		}
	}

	private void Update()
	{
		if (IsAttackerInLane())
		{
			animator.SetBool("isAttacking", true);
		} else
		{
			animator.SetBool("isAttacking", false);
		}
	}

	private void SetLaneSpawner()
	{
		AttackerSpawner[] spawners = FindObjectsOfType<AttackerSpawner>();
		foreach (AttackerSpawner spawner in spawners)
		{
			bool IsCloseEnough = (Mathf.Abs(spawner.transform.position.y - transform.position.y) <= Mathf.Epsilon);
			if (IsCloseEnough)
			{
				myLaneSpawner = spawner;
			}
		}
	}

	private bool IsAttackerInLane()
	{
		return myLaneSpawner.transform.childCount > 0;
	}

	public void Fire()
	{
		GameObject newProjectile = Instantiate(projectile, gun.transform.position, Quaternion.identity) as GameObject;
		newProjectile.transform.parent = projectileParent.transform;
	}
}
